export const data = [
    {
        "id": "0",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg",
        "full_name": "Uniswap",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Protocol",
        "TVL": "562397",
        "date_founded": "April 2018",
        "date_created": "April 2018",
        "website": "website@website.com",
        "blockchain": "Ethereum",
        "headquarters": "Earth"
      },
      {
        "id": "1",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1152363392595714048%2FOVJu6nwQ_normal.png",
        "full_name": "Compound",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Protocol",
        "TVL": "156535",
        "date_founded": "May 2011",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Waves",
        "headquarters": "Earth"
      },
      {
        "id": "2",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1186270065085370368%2FJ1YJtvdI_normal.jpg",
        "full_name": "Aave",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Protocol",
        "TVL": "248054",
        "date_founded": "May 2017",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Ripple",
        "headquarters": "Earth"
      },
      {
        "id": "3",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1392501414887313409%2FixijGeIo_normal.jpg",
        "full_name": "Badger",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Protocol",
        "TVL": "35724",
        "date_founded": "August 2020",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Stellar",
        "headquarters": "Earth"
      },
      {
        "id": "4",
        "logo_link": "https://bit.ly/3ILKK4d",
        "full_name": "SushiChef",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Protocol",
        "TVL": "110453",
        "date_founded": "September 2020",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Solana",
        "headquarters": "Earth"
      },
      {
        "id": "5",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1242184851152928769%2FwG2eTAfD_normal.jpg",
        "full_name": "Duoswap",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Service",
        "TVL": "562397",
        "date_founded": "April 2018",
        "date_created": "April 2018",
        "website": "website@website.com",
        "blockchain": "Ethereum",
        "headquarters": "Earth",
        "dao_structure": "Structure",
        "voting_process": "2-way",
        "revenue_streams": "Multiple"
      },
      {
        "id": "6",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1152363392595714048%2FOVJu6nwQ_normal.png",
        "full_name": "Compound",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Service",
        "TVL": "156535",
        "date_founded": "May 2011",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Waves",
        "headquarters": "Earth",
        "dao_structure": "Structure",
        "voting_process": "2-way",
        "revenue_streams": "Multiple"
      },
      {
        "id": "7",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1186270065085370368%2FJ1YJtvdI_normal.jpg",
        "full_name": "Weave",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Grant",
        "TVL": "248054",
        "date_founded": "May 2017",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Ripple",
        "headquarters": "Earth",
        "dao_structure": "Structure",
        "voting_process": "2-way",
        "revenue_streams": "Multiple"
      },
      {
        "id": "8",
        "logo_link": "https://daolist.fyi/nextimg/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1392501414887313409%2FixijGeIo_normal.jpg",
        "full_name": "Honey Badger",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Grant",
        "TVL": "35724",
        "date_founded": "August 2020",
        "date_created": "May 2020",
        "website": "website@website.com",
        "blockchain": "Stellar",
        "headquarters": "Earth",
        "dao_structure": "Structure",
        "voting_process": "2-way",
        "revenue_streams": "Multiple"
      },
      {
        "id": "9",
        "logo_link": "https://bit.ly/3ILKK4d",
        "full_name": "SousChef",
        "description": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed",
        "category": "Service",
        "TVL": "110453",
        "date_founded": "September 2020",
        "date_created": "May 2000",
        "website": "website@website.com",
        "blockchain": "Solana",
        "headquarters": "Earth",
        "dao_structure": "Structure",
        "voting_process": "2-way",
        "revenue_streams": "Multiple"
      }
]
//https://sushi.com/static/media/logo.dec926df.png